platform :ios, '10.3'

target 'example' do

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'ART',
    'RCTImage',
  ]

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == 'yoga'
          target.build_configurations.each do |config|
              config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
              config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
          end
      end
      if target.name == 'React'
          target.remove_from_project
      end
  end
end
